version: 2
updates:
  - package-ecosystem: "pip" 
    directory: "/" # Location of package manifests
    schedule:
      interval: "weekly"
      time: "13:00"
      timezone: "Europe/Copenhagen"
     # Add assignees
    assignees:
      - "hiyama341"
      - "sorpet"
