[tox]
envlist = py310, py311, py312, py313, py314, flake8

[gh-actions]
python =
    3.10: py310
    3.11: py311
    3.12: py312
    3.13: py313
    3.14: py314

[testenv:flake8]
basepython = python
deps = flake8
commands = flake8 teemi tests

[testenv]
setenv =
    PYTHONPATH = {toxinidir}
deps =
    -r{toxinidir}/requirements.txt
    pytest
    pytest-cov
    seaborn
    scipy
commands =
    pytest --basetemp={envtmpdir} {posargs}
